name: 'Execute workflow'
description: 'Executes particular workflow by id'
author: 'Chassy'

inputs:
  workflowId:
    description: 'The id of the specified workflow'
    required: true
  parameters:
    description: 'Parameters with any fields in JSON format'
    required: false

outputs:
  workflowExecution:
    description: 'Workflow execution result'

runs:
  using: node20
  main: dist/index.js
