name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    env:
      CHASSY_TOKEN: ${{ secrets.CHASSY_ACCESS_TOKEN }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          workflowId: 'workflow-be690a244173415aad00258b852fb2d5'
          chassyToken: 'eyJraWQiOiJ6a2QrV3FsNUg5S2J0dG1UYUJMcEdISUFuVDBEaDBNc3ByQ1wvU3NxRm9hWT0iLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiN0JmUjFleHkyYkJCREc3UkltWWN6USIsInN1YiI6IjQ4OGI0ZjEwLTFmNzUtNDFkMC1iMDkyLTI4ZjRjN2NkYWYzNCIsImNvZ25pdG86Z3JvdXBzIjpbInVzLXdlc3QtMl9hVGowbFpVdnJfR29vZ2xlIl0sImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtd2VzdC0yLmFtYXpvbmF3cy5jb21cL3VzLXdlc3QtMl9hVGowbFpVdnIiLCJjb2duaXRvOnVzZXJuYW1lIjoiR29vZ2xlXzExNDc4NzQzMDk5Mzc0MDk4MzE3NiIsImdpdmVuX25hbWUiOiLQotC10LzRg9GH0LjQvSIsInBpY3R1cmUiOiJodHRwczpcL1wvbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbVwvYVwvQUNnOG9jSlZIZGlGVXVmY2RjNFlLeXp6QWFIOW83UVlIdmZSTFR2dmFaYkZwOXVsNkJTNE9RPXM5Ni1jIiwib3JpZ2luX2p0aSI6Ijc5NDc4MjM2LTgwMjEtNGM0ZC04NGM3LWI3MDMxZWNlMzMzZCIsImF1ZCI6IjNmOGpxbWVna2c4MnFuaXNyYWZxbzdyaTNqIiwiaWRlbnRpdGllcyI6W3sidXNlcklkIjoiMTE0Nzg3NDMwOTkzNzQwOTgzMTc2IiwicHJvdmlkZXJOYW1lIjoiR29vZ2xlIiwicHJvdmlkZXJUeXBlIjoiR29vZ2xlIiwiaXNzdWVyIjpudWxsLCJwcmltYXJ5IjoidHJ1ZSIsImRhdGVDcmVhdGVkIjoiMTcxNDU3OTUwMDI1MiJ9XSwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE3MTQ2Njc0NjIsImV4cCI6MTcxNzEwMjM0MiwiaWF0IjoxNzE3MDU5MTQyLCJmYW1pbHlfbmFtZSI6ItCi0L7RgNGH0LXQvdGO0LoiLCJqdGkiOiI3MzZkMWQwMS0wNDc2LTQwZTAtYWE2Mi0xMzcyNWU4MDJmY2IiLCJlbWFpbCI6InRlbXVjaGluMjZAZ21haWwuY29tIn0.mQdr417DeiQJTtMhdQRLozEHlL0Fb3EHLQil7Ptnt-h9Yvh0mvXIZGKn7rmdh_ZBSZDHXNVlPqg4SL1NVBpB_B15SFcjGgMWWWIrw007HZa6Zi7IY9KEhQcAh5QiZgyDDnODp6nf9x0wGXHCc7AlydkGP3MX2khVkRGI8g3eBU2nsPPe6VNO-A-uKpgx4OSqaI24bHrm5MTNsPf0cCIxYkTCWWyCn15k0OFvZxhhTHz7J0tLieDWxDFemmfICNenqrorMxi3ZCfLDbmUr-w3hwgw7JYgnoUccB8zhL_tLYbdC8kn5n02K-RyWaQAe1tKl_lEaRY34V2vThoONY7laA'
        env:
          STEP_ENV_VAR: 'step_value'

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.workflowexecution }}"
