name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  # uncomment for manual testing
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    env:
      CHASSY_TOKEN: eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUlNBLU9BRVAifQ.M9p9ghJEJ87YBM3gxb_jDKs71zDRxEVuq2lgNciXy3mVtzkt_lP-YoH3tGeU9HUVjgpjz8-W8Su7B3M73-wDbZm-LY-k0jxESEWcfNo1cq3i0BzLw1P3BfjHREn9ikRVqrtcstBJ4w0AfMnL6R2m0fcHWF86cIg43QhQm5UBO_7A_BNxPQ_TWXWTgO0muGDehNWFKGLwSSyOQZ55l6g7egXWjsKOoTbmGt5bYjhYn8ae5-a89JGeRyyo0w8lRTMV1d5zLMQe7DQ9usP07O5VpVgn2ComZY4rE6CZeURFPbs-1n2q7GHJYZsKMEOtSDtvEv12Zt9P2BvB2tqIHcdrDA.Pqz0GF_rk_MRwnji.ubust6abrDHUGUje39AFSnOPRq0yd9spJLNP5YsZCuE_Yqj3QKu0yoj8di21JBZEvQYbmIugoCsbPD7oPrU-2-83Xu0zyR8360uYz1aLCrOiD5jVyJnppxxQ7w5T-ChpJVAGLKMNvkLx1iFXr37-El4kcCW5gUbSQ_G0riBc9AuApDFshe0nSFH2nKcP3AzT-jBmu6auTS9uPDioOAQkg9D67kVtfz6Gbo8aCAK_2Ywa8GO37nIMLDyFdskYbdS6ImzPK4UdkNrAwYtjLV5M4E18U4cLymU9T9i97nQBTR7s-dQK3gkhCYbwC1vGgLwjCjmFUTr6O4bQRWDL1_Tgc4PHOYlnYRl-KfTgqZu372PYR07ykfsxRG2EX6YRHq1xnk2hdh6eXW-2wz8kVj8eZnrpv-95hy89inI7IWVVXJw_SCzoKb2sBMTx0cs8Or2SBmufG6myIBdTXmCA0fTq-rL1PxAqjKZpY-kiCamh6Q5t4d8rkDWCNFb1A_8_KYS31-XHdpLo8_th1dR2GR19V8c0NKSGKoclPb-QOLtKAF-BIq9r_gEjeyEYqJmmTMZkFqqP7e9X7F_q2ory0TI-lPdgtOZeMKr9vsmsDwcIAEHn3btV-WB0ntw1_Yry_rzvmJ-gESioiHWfhcMAU_1c3NS60jaGxROsoI6tP5T8gPRkwtITmqokqSBWmhs9cthLeX2zSmbQwmWqDtltUuyjXekN61xXx2KvpLiYlrvjo7OycZm2lDgDA5wlYF22ylhzQkP-UkPKUVjLMa-vZaIpc73fsNFXy3S-loOUVCke2m13cs2-InCwZ0A8snIYrP_iexuLtmsUJfxksjsAdsVTuslVwed3aCIEqVKHxeQFEOHD22cYH93ctg6WXAwZW3j6PohHblGYAFB4etg034X4F8w5x_eVi2oaYpG22lt5QF4rxnc2ybZVWihH2JlV6CPUKGF7S8gK6qFbQPV8PkQaqpTo78fF6dz6Z4NEq_llp_nlKU38cQA25yJnAzRaYsvBudmSA3JCtmOA7kNZkk1ZlLLEYtorJ93gXM01MsZWQZYcS2oKvyjkiWhtkmsFBumKpBxoK5in7OZAHemQVb5Is9q0SlU4_AVR6vXy_-_3aJqRIniHFaQssrI6fk9KAH3AwloCpKBdi_12yKCtnx0Ib8dd_MAIDRD9pUtcjBVq08cK-ZWS87af7Q7xe679So__-k4vQ0mdSQj5BlanLkd9nfJPsYNigfz3uIpunD-KPiGnmE1k2GjrAZNZpK9YVaRHPCY1OKU-jbil-g.Y15Le7zVjVbipgWq0kZS_Q

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          workflowId: 'workflow-c2f522acc2534d639827970d8c2034ee'
          backendEnvironment: 'DEV'
      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.workflowexecution }}"
